cadena=input("Ingresa un texto:")
print("El caracter en primer lugar es:", cadena[0]) 
print("Ingresa un numero positivo menor a", len(cadena)) 
indice = int(input())
print("El caracter en esa posición es:", cadena[indice])